### ISSUE TITLE
The new /delete command doesn't get logged..

### ISSUE THREAD

**Issue by mattts1** [Equinoxbig/twitch-moderation-pubsub#3]
Dunno if its native to Twitch or a FFZ command but its an actual purge command that isn't just a 1 second timeout. If it isn't native could it still get logged anyway so I can use it.

Thanks!

**Comment by mdolr** [comment]
Can you give me more informations about the "/delete" command ? I've never heard of it and can't seem to find it when typing /help in chat with bttv & frankerfacez installed and the description given by twitch isn't really helping me

**Comment by mattts1** [comment]
Check the changelog for FFZ, thats the only place I've seen it mentioned. I setup an in-line action button in FFZ, right next to the timeout and ban buttons next to a persons name. Its pretty much a purge button but instead of saying in chat that its a 1 second timeout, it presents a message in chat that only the mods/streamer can see, even people without FFZ, that a particular message has been deleted. 

I haven't actually used the text command though since FFZ let me create a button for it instead.

**Comment by mdolr** [comment]
Well it seems related to FrankerFaceZ only and not to twitch pubsub so I guess there is no way to catch delete events.

**Comment by mattts1** [comment]
This is a twitch command: 
https://dev.twitch.tv/docs/irc/commands/#clearmsg-twitch-commands

**Comment by mdolr** [comment]
Thanks the for the link,
I was able to implement it : 

```js
your_pubsub.on('delete', (data) => {
  console.log(data);
})

// and data scheme : 
{
  channel_id: 'id_to_string',
  type: 'delete',
  moderator: { id: 'id_to_string', name: 'username' },
  target: { id: 'id_to_string', name: 'username' },
  message: { content: 'content to string', id: 'uuid_to_string' },
  created_at: Number (timestamp)
}
```

**Comment by mattts1** [comment]
Has this change been added to the live bot yet? Because its still not getting logged..

**Comment by mdolr** [comment]
This repository has nothing to do with any bot, it is just a nodeJS library.

**Comment by mattts1** [comment]
My apologies! Wrong github..
